# Generated by Django 3.2.6 on 2021-08-11 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20210811_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
